services:
  local-cloud:
    build: .
    ports:
      - "4170:4170"
    volumes:
      - ./config.json:/app/config.json
      - ./data:/app/data
      - ./test-data:/app/test-data
      - /:/host:ro
